# Generated by Django 5.1.7 on 2026-09-09 14:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(help_text='Class start time')),
                ('end_time', models.TimeField(help_text='Class end time')),
                ('max_students', models.PositiveIntegerField(default=20, help_text='Maximum number of students allowed in this class')),
                ('days', models.JSONField(blank=True, default=list, help_text='Days when this class runs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must start with +62 and contain 9-13 digits.', regex='^\\+62\\d{9,13}$')])),
                ('address', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Mix Class', 'Mix Class'), ('Beginner 1', 'Beginner 1'), ('Beginner 2', 'Beginner 2'), ('Elementary 1', 'Elementary 1'), ('Elementary 2', 'Elementary 2'), ('Elementary 3', 'Elementary 3'), ('Junior 1', 'Junior 1'), ('Junior 2', 'Junior 2'), ('Junior 3', 'Junior 3'), ('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3')], max_length=20)),
                ('email', models.EmailField(blank=True, help_text="Email used for the student's e-learning login.", max_length=254)),
                ('user', models.OneToOneField(blank=True, help_text='Linked e-learning account, if one has been provisioned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentclass')),
            ],
        ),
    ]
