# Generated by Django 5.1.7 on 2025-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentclass_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='days',
            field=models.JSONField(blank=True, default=list, help_text='Days when this class runs'),
        ),
    ]
