# Generated by Django 5.1.7 on 2026-09-09 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_installment', models.BooleanField(default=False)),
                ('current_installment', models.IntegerField(default=0, help_text='Current installment number')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, help_text='Year this configuration applies to', validators=[django.core.validators.MinValueValidator(2020)])),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, help_text='Monthly payment fee in IDR', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_installments', models.IntegerField(default=3, help_text='Maximum number of installments allowed per payment', validators=[django.core.validators.MinValueValidator(1)])),
                ('minimum_payment_amount', models.DecimalField(decimal_places=2, default=50000, help_text='Minimum payment amount per installment in IDR', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('mid_semester_start', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('mid_semester_end', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('final_semester_start', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('final_semester_end', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('year', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='The installment number (e.g., 1st, 2nd, 3rd installment)', validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for this specific installment', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='When this installment was recorded')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.payment')),
            ],
            options={
                'ordering': ['payment', 'installment_number'],
                'unique_together': {('payment', 'installment_number')},
            },
        ),
    ]
