# Generated by Django 5.1.7 on 2025-04-17 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, help_text='Monthly payment fee in IDR', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('mid_semester_start', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('mid_semester_end', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('final_semester_start', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('final_semester_end', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['year', 'month']},
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.IntegerField(),
        ),
    ]
