# Generated by Django 5.1.7 on 2025-04-20 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentconfig_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='year',
            field=models.IntegerField(default=2025, help_text='Year this configuration applies to', validators=[django.core.validators.MinValueValidator(2020)]),
        ),
        migrations.AlterUniqueTogether(
            name='paymentconfig',
            unique_together={('year', 'is_active')},
        ),
    ]
