# Generated by Django 5.1.7 on 2025-04-30 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentconfig_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='current_installment',
            field=models.IntegerField(default=0, help_text='Current installment number'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='max_installments',
            field=models.IntegerField(default=2, help_text='Maximum number of installments allowed per payment', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
