# Generated by Django 5.1.7 on 2025-04-30 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_current_installment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='The installment number (e.g., 1st, 2nd, 3rd installment)', validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for this specific installment', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='When this installment was recorded')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.payment')),
            ],
            options={
                'ordering': ['payment', 'installment_number'],
                'unique_together': {('payment', 'installment_number')},
            },
        ),
    ]
