# Generated by Django 5.1.7 on 2025-05-08 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentinstallment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfig',
            name='max_installments',
            field=models.IntegerField(default=3, help_text='Maximum number of installments allowed per payment', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
