# Generated by Django 5.1.7 on 2025-05-28 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentconfig_max_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='minimum_payment_amount',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Minimum payment amount per installment in IDR', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
