# Generated by Django 5.1.7 on 2026-08-21 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentconfig_minimum_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfig',
            name='year',
            field=models.IntegerField(default=2026, help_text='Year this configuration applies to', validators=[django.core.validators.MinValueValidator(2020)]),
        ),
    ]
