# Generated by Django 5.1.7 on 2026-09-09 14:13

import django.core.validators
import django.db.models.deletion
import study_materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF document'), ('video', 'Video'), ('write_up', 'Write-up')], default='pdf', max_length=20)),
                ('content', models.TextField(blank=True, help_text='The lesson content for a write-up material.')),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=20)),
                ('level', models.CharField(choices=[('Mix Class', 'Mix Class'), ('Beginner 1', 'Beginner 1'), ('Beginner 2', 'Beginner 2'), ('Elementary 1', 'Elementary 1'), ('Elementary 2', 'Elementary 2'), ('Elementary 3', 'Elementary 3'), ('Junior 1', 'Junior 1'), ('Junior 2', 'Junior 2'), ('Junior 3', 'Junior 3'), ('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to=study_materials.models.study_material_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'mp4', 'webm', 'mov', 'm4v'))])),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=study_materials.models.study_material_thumbnail_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Manual ordering within a level and category.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('student_class', models.ForeignKey(blank=True, help_text='Restrict to a single class. Leave empty to target the whole level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='students.studentclass')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status', 'level', 'category'], name='study_material_visible_idx'), models.Index(fields=['position'], name='study_material_position_idx')],
            },
        ),
    ]
