# Generated by Django 5.1.7 on 2025-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0003_alter_studymaterial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='study_material_thumbnails/'),
        ),
    ]
