# Generated by Django 5.1.7 on 2025-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0004_studymaterial_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Study Material', 'verbose_name_plural': 'Study Materials'},
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='level',
            field=models.CharField(choices=[('Mix Class', 'Mix Class'), ('Beginner 1', 'Beginner 1'), ('Beginner 2', 'Beginner 2'), ('Elementary 1', 'Elementary 1'), ('Elementary 2', 'Elementary 2'), ('Elementary 3', 'Elementary 3'), ('Junior 1', 'Junior 1'), ('Junior 2', 'Junior 2'), ('Junior 3', 'Junior 3'), ('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3')], default='Beginner 1', max_length=20),
            preserve_default=False,
        ),
    ]
