# Generated by Django 5.1.7 on 2026-08-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def backfill_slug_and_status(apps, schema_editor):
    """
    Give existing rows a unique slug before uniqueness is enforced, and treat
    the existing library as already published -- these materials were live
    before ``status`` existed, so defaulting them to draft would hide them.
    """
    StudyMaterial = apps.get_model("study_materials", "StudyMaterial")

    taken = set()
    to_update = []
    now = timezone.now()

    for material in StudyMaterial.objects.order_by("pk").only("id", "title", "slug"):
        base = slugify(material.title)[:250] or "material"
        slug = base
        suffix = 2
        while slug in taken:
            slug = f"{base}-{suffix}"
            suffix += 1
        taken.add(slug)

        material.slug = slug
        material.status = "published"
        material.published_at = now
        to_update.append(material)

    if to_update:
        StudyMaterial.objects.bulk_update(
            to_update, ["slug", "status", "published_at"], batch_size=500
        )
        print(f"  slugged and published {len(to_update)} existing material(s)")


def clear_slugs(apps, schema_editor):
    """Reverse of the backfill; the columns are dropped right after."""
    StudyMaterial = apps.get_model("study_materials", "StudyMaterial")
    StudyMaterial.objects.update(slug="", status="draft", published_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_email_student_user'),
        ('study_materials', '0005_alter_studymaterial_options_studymaterial_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Manual ordering within a level and category.'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Added without `unique` (and without an index) so existing rows can be
        # slugged first. SlugField implies db_index=True, and leaving it on here
        # would create the varchar_pattern_ops "_like" index that the AlterField
        # below also wants -- same name, same transaction, hard failure.
        migrations.AddField(
            model_name='studymaterial',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=280, db_index=False),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='Restrict to a single class. Leave empty to target the whole level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='students.studentclass'),
        ),
        migrations.RunPython(backfill_slug_and_status, clear_slugs),
        migrations.AlterField(
            model_name='studymaterial',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='category',
            field=models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['status', 'level', 'category'], name='study_material_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['position'], name='study_material_position_idx'),
        ),
    ]
