# Generated by Django 5.1.7 on 2026-08-22 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0006_studymaterial_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='content',
            field=models.TextField(blank=True, help_text='The lesson content for a write-up material.'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF document'), ('video', 'Video'), ('write_up', 'Write-up')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, upload_to='study_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'mp4', 'webm', 'mov', 'm4v'))]),
        ),
    ]
