# Generated by Django 5.1.7 on 2026-08-22 14:01

import core.storage
import django.core.validators
import study_materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0007_studymaterial_content_studymaterial_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, storage=core.storage.study_material_storage, upload_to=study_materials.models.study_material_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'mp4', 'webm', 'mov', 'm4v'))]),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=core.storage.study_material_storage, upload_to=study_materials.models.study_material_thumbnail_upload_to),
        ),
    ]
