"""
Django settings for afidu project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from urllib.parse import urlparse
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yq(deq^unt6j#^fv5jkvs9iqaic)$r1_3&29*sa%(oc0m@^w1r"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "widget_tweaks",
    "login",
    "register",
    "myprofile",
    "dashboard",
    "students",
    "scores",
    "reports",
    "study_materials",
    "assignments",
    "payments",
    "documents",
    "administrators",
    "compressor",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "afidu.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "afidu.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# comment the below DATABASES setting to use sqlite
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# uncomment the below DATABASES setting to use PostgreSQL
DATABASE_URL = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DATABASE_URL.path.replace('/', ''),
        'USER': DATABASE_URL.username,
        'PASSWORD': DATABASE_URL.password,
        'HOST': DATABASE_URL.hostname,
        'PORT': DATABASE_URL.port,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Jakarta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Media storage. Backblaze B2 exposes an S3-compatible endpoint, so uploads can
# use django-storages. With no B2 settings development continues to use MEDIA_ROOT.
_b2_endpoint = os.getenv("B2_ENDPOINT_URL", "").rstrip("/")
B2_ENDPOINT_URL = (
    f"https://{_b2_endpoint}"
    if _b2_endpoint and "://" not in _b2_endpoint
    else _b2_endpoint
)
B2_REGION_NAME = os.getenv("B2_REGION_NAME", "")
B2_BUCKET_NAME = os.getenv("B2_BUCKET_NAME", "")
B2_KEY_ID = os.getenv("B2_KEY_ID", "")
B2_APPLICATION_KEY = os.getenv("B2_APPLICATION_KEY", "")
B2_PUBLIC_URL = os.getenv("B2_PUBLIC_URL", "").rstrip("/")

_b2_required = {
    "B2_ENDPOINT_URL": B2_ENDPOINT_URL,
    "B2_REGION_NAME": B2_REGION_NAME,
    "B2_BUCKET_NAME": B2_BUCKET_NAME,
    "B2_KEY_ID": B2_KEY_ID,
    "B2_APPLICATION_KEY": B2_APPLICATION_KEY,
}
USE_B2 = all(_b2_required.values())

if any(_b2_required.values()) and not USE_B2:
    missing = ", ".join(name for name, value in _b2_required.items() if not value)
    raise ImproperlyConfigured(
        f"Backblaze B2 is only partially configured. Missing: {missing}."
    )

if USE_B2:
    if not B2_ENDPOINT_URL.startswith("https://"):
        raise ImproperlyConfigured("B2_ENDPOINT_URL must be an HTTPS URL.")

    public_domain = None
    if B2_PUBLIC_URL:
        parsed_public_url = urlparse(B2_PUBLIC_URL)
        public_domain = parsed_public_url.netloc or parsed_public_url.path

    b2_storage_options = {
        "access_key": B2_KEY_ID,
        "secret_key": B2_APPLICATION_KEY,
        "bucket_name": B2_BUCKET_NAME,
        "endpoint_url": B2_ENDPOINT_URL,
        "region_name": B2_REGION_NAME,
        "signature_version": "s3v4",
        "addressing_style": "virtual",
        # B2 applies ACLs at bucket level; do not send per-object ACLs.
        "default_acl": None,
        "object_parameters": {"CacheControl": "max-age=86400"},
        "querystring_auth": public_domain is None,
        "querystring_expire": int(os.getenv("B2_URL_EXPIRE_SECONDS", "3600")),
        "custom_domain": public_domain,
        "url_protocol": "https:",
    }

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {**b2_storage_options, "file_overwrite": False},
        },
        # Study-material object names contain UUIDs. Skipping overwrite checks
        # avoids an unnecessary HeadObject request before every upload.
        "study_materials": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {**b2_storage_options, "file_overwrite": True},
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "study_materials": {
            "BACKEND": "django.core.files.storage.FileSystemStorage"
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        },
    }

LOGIN_URL = reverse_lazy("login:login")
LOGIN_REDIRECT_URL = reverse_lazy("dashboard:dashboard")
LOGOUT_REDIRECT_URL = reverse_lazy("login:login")

AUTH_USER_MODEL = "login.CustomUser"

# Every student gets an account automatically (see students/signals.py)
# student emails are derived from their name on this domain,
# it is not routable, so no mail is ever delivered to it
STUDENT_LOGIN_EMAIL_DOMAIN = os.getenv("STUDENT_LOGIN_EMAIL_DOMAIN", "afidu.local")
# Shared starting password
STUDENT_DEFAULT_PASSWORD = os.getenv("STUDENT_DEFAULT_PASSWORD", "1234")

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

COMPRESS_ROOT = BASE_DIR / "static"

COMPRESS_ENABLED = True

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
