# Generated by Django 5.1.7 on 2025-03-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('Odd', 'Odd Semester'), ('Even', 'Even Semester')], max_length=4)),
                ('category', models.CharField(choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Listening', 'Listening'), ('Speaking', 'Speaking')], max_length=20)),
                ('E1', models.PositiveIntegerField(default=0)),
                ('E2', models.PositiveIntegerField(default=0)),
                ('E3', models.PositiveIntegerField(default=0)),
                ('E4', models.PositiveIntegerField(default=0)),
                ('E5', models.PositiveIntegerField(default=0)),
                ('E6', models.PositiveIntegerField(default=0)),
                ('mid_term', models.PositiveIntegerField(default=0)),
                ('finals', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student')),
            ],
        ),
    ]
