# Generated by Django 5.1.7 on 2026-09-09 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('mid', 'MID'), ('final', 'FINAL')], max_length=5, null=True)),
                ('category', models.CharField(blank=True, choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=10, null=True)),
                ('num_exercises', models.PositiveIntegerField(default=5)),
                ('formula', models.TextField(default='0.30 * (ex_sum / num_exercises) + 0.30 * mid_term + 0.40 * finals')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('mid', 'MID'), ('final', 'FINAL')], max_length=5)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=10)),
                ('legacy_exercise_scores', models.JSONField(blank=True, default=list)),
                ('mid_term', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('mid_term_source', models.CharField(choices=[('manual', 'Manual'), ('assignment', 'Assignment'), ('quiz', 'Quiz')], default='manual', max_length=20)),
                ('mid_term_note', models.CharField(blank=True, max_length=255)),
                ('finals', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('finals_source', models.CharField(choices=[('manual', 'Manual'), ('assignment', 'Assignment'), ('quiz', 'Quiz')], default='manual', max_length=20)),
                ('finals_note', models.CharField(blank=True, max_length=255)),
                ('finals_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_scores', to='assignments.assignment')),
                ('mid_term_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mid_term_scores', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='1-indexed exercise position.')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('assignment', 'Assignment'), ('quiz', 'Quiz')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to='assignments.assignment')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scores.score')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'score entry',
                'verbose_name_plural': 'score entries',
                'ordering': ['score', 'slot'],
            },
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['year', 'semester', 'category'], name='score_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('student', 'year', 'semester', 'category'), name='score_student_period_category_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.UniqueConstraint(fields=('score', 'slot'), name='score_entry_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.CheckConstraint(condition=models.Q(('slot__gte', 1)), name='score_entry_slot_min'),
        ),
    ]
