# Generated by Django 5.1.7 on 2025-03-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_score_unique_together_alter_score_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_exercises', models.PositiveIntegerField(default=6)),
                ('formula', models.TextField(default='(ex_sum + mid_term + finals) / (num_exercises + 2)')),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='e1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='e2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='e3',
        ),
        migrations.RemoveField(
            model_name='score',
            name='e4',
        ),
        migrations.RemoveField(
            model_name='score',
            name='e5',
        ),
        migrations.RemoveField(
            model_name='score',
            name='e6',
        ),
        migrations.AddField(
            model_name='score',
            name='exercise_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
