# Generated by Django 5.1.7 on 2025-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_scoreconfig_remove_score_e1_remove_score_e2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='semester',
            field=models.CharField(choices=[('mid', 'MID'), ('final', 'FINAL')], max_length=5),
        ),
    ]
