# Generated by Django 5.1.7 on 2025-04-19 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_alter_score_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='finals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='mid_term',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='scoreconfig',
            name='num_exercises',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
