# Generated by Django 5.1.7 on 2025-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_alter_score_finals_alter_score_mid_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreconfig',
            name='category',
            field=models.CharField(blank=True, choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scoreconfig',
            name='semester',
            field=models.CharField(blank=True, choices=[('mid', 'MID'), ('final', 'FINAL')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='scoreconfig',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
