# Generated by Django 5.1.7 on 2025-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_scoreconfig_category_scoreconfig_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreconfig',
            name='formula',
            field=models.TextField(default='0.30 * (ex_sum / num_exercises) + 0.30 * mid_term + 0.40 * finals'),
        ),
    ]
