# Generated by Django 5.1.7 on 2026-08-21 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('scores', '0009_dedupe_scores'),
        ('students', '0009_student_email_student_user'),
        ('study_materials', '0006_studymaterial_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='1-indexed exercise position.')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('assignment', 'Assignment'), ('material', 'Study material'), ('quiz', 'Quiz')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'score entry',
                'verbose_name_plural': 'score entries',
                'ordering': ['score', 'slot'],
            },
        ),
        migrations.RenameField(
            model_name='score',
            old_name='exercise_scores',
            new_name='legacy_exercise_scores',
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['year', 'semester', 'category'], name='score_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('student', 'year', 'semester', 'category'), name='score_student_period_category_uniq'),
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to='study_materials.studymaterial'),
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scores.score'),
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to='assignments.submission'),
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.UniqueConstraint(fields=('score', 'slot'), name='score_entry_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.CheckConstraint(condition=models.Q(('slot__gte', 1)), name='score_entry_slot_min'),
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.CheckConstraint(condition=models.Q(('assignment__isnull', True), ('material__isnull', True), _connector='OR'), name='score_entry_single_source'),
        ),
    ]
