# Generated by Django 5.1.7 on 2026-08-23 14:37

from django.db import migrations, models


def drop_material_source(apps, schema_editor):
    """Entries that named a study material as their source are now plain manual."""
    ScoreEntry = apps.get_model("scores", "ScoreEntry")
    ScoreEntry.objects.filter(source="material").update(source="manual")


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_backfill_score_entries'),
    ]

    operations = [
        migrations.RunPython(drop_material_source, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='scoreentry',
            name='score_entry_single_source',
        ),
        migrations.RemoveField(
            model_name='scoreentry',
            name='material',
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('assignment', 'Assignment'), ('quiz', 'Quiz')], default='manual', max_length=20),
        ),
    ]
