# Generated by Django 5.1.7 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0006_assignment_score_target"),
        ("scores", "0012_remove_scoreentry_score_entry_single_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="finals_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="final_scores",
                to="assignments.assignment",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="finals_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="score",
            name="finals_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("assignment", "Assignment"),
                    ("quiz", "Quiz"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="mid_term_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mid_term_scores",
                to="assignments.assignment",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="mid_term_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="score",
            name="mid_term_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("assignment", "Assignment"),
                    ("quiz", "Quiz"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
