# Generated by Django 5.1.7 on 2026-08-21 15:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0009_student_email_student_user'),
        ('study_materials', '0006_studymaterial_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('normal', 'Normal'), ('essay', 'Essay'), ('objective', 'Objective'), ('quiz', 'Quiz'), ('file_upload', 'File upload')], default='normal', max_length=20)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=20)),
                ('level', models.CharField(choices=[('Mix Class', 'Mix Class'), ('Beginner 1', 'Beginner 1'), ('Beginner 2', 'Beginner 2'), ('Elementary 1', 'Elementary 1'), ('Elementary 2', 'Elementary 2'), ('Elementary 3', 'Elementary 3'), ('Junior 1', 'Junior 1'), ('Junior 2', 'Junior 2'), ('Junior 3', 'Junior 3'), ('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3')], max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('mid', 'MID'), ('final', 'FINAL')], max_length=5, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Timed quizzes only. Leave empty for untimed work.', null=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('allow_late', models.BooleanField(default=False)),
                ('allow_file_upload', models.BooleanField(default=False)),
                ('auto_grade', models.BooleanField(default=False, help_text='Score objective questions on submit.')),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('reveal_answers_after_submit', models.BooleanField(default=False)),
                ('max_points', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, help_text='Reference material students should read for this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='study_materials.studymaterial')),
                ('student_class', models.ForeignKey(blank=True, help_text='Restrict to a single class. Leave empty to target the whole level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='students.studentclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('multi_select', 'Multi select'), ('true_false', 'True / false'), ('short_text', 'Short text'), ('essay', 'Essay'), ('file_upload', 'File upload')], default='multiple_choice', max_length=20)),
                ('prompt', models.TextField()),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('explanation', models.TextField(blank=True, help_text='Shown after submission when answers are revealed.')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
            ],
            options={
                'ordering': ['assignment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('awarded_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='assignments.questionchoice')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='multi_answers', to='assignments.questionchoice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.submission')),
            ],
            options={
                'ordering': ['submission', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, help_text='Set when the upload answers one specific question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='assignments.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.submission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'level', 'category'], name='assignment_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_at'], name='assignment_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__isnull', True), ('open_at__isnull', True), ('due_at__gt', models.F('open_at')), _connector='OR'), name='assignment_due_after_open'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_minutes__isnull', True), ('time_limit_minutes__gt', 0), _connector='OR'), name='assignment_time_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='assignment_max_attempts_min'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('assignment', 'order'), name='question_assignment_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='choice_question_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'status'], name='submission_asg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='submission_stu_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student', 'attempt_number'), name='submission_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='submission_attempt_min'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='answer_submission_question_uniq'),
        ),
        migrations.AddIndex(
            model_name='submissionfile',
            index=models.Index(fields=['submission'], name='submission_file_sub_idx'),
        ),
    ]
