# Generated by Django 5.1.7 on 2026-09-09 14:13

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=20)),
                ('level', models.CharField(choices=[('Mix Class', 'Mix Class'), ('Beginner 1', 'Beginner 1'), ('Beginner 2', 'Beginner 2'), ('Elementary 1', 'Elementary 1'), ('Elementary 2', 'Elementary 2'), ('Elementary 3', 'Elementary 3'), ('Junior 1', 'Junior 1'), ('Junior 2', 'Junior 2'), ('Junior 3', 'Junior 3'), ('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3')], max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('mid', 'MID'), ('final', 'FINAL')], max_length=5, null=True)),
                ('score_target', models.CharField(blank=True, choices=[('exercise_1', 'Exercise 1'), ('exercise_2', 'Exercise 2'), ('exercise_3', 'Exercise 3'), ('exercise_4', 'Exercise 4'), ('exercise_5', 'Exercise 5'), ('exercise_6', 'Exercise 6'), ('exercise_7', 'Exercise 7'), ('exercise_8', 'Exercise 8'), ('exercise_9', 'Exercise 9'), ('exercise_10', 'Exercise 10'), ('mid_term', 'Mid Term'), ('finals', 'Finals')], help_text='Score field updated when a submission is marked.', max_length=11, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes allowed once started. Leave empty for untimed work.', null=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('allow_late', models.BooleanField(default=False)),
                ('allow_file_upload', models.BooleanField(default=False)),
                ('auto_grade', models.BooleanField(default=False, help_text='Score objective questions on submit.')),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('reveal_answers_after_submit', models.BooleanField(default=False)),
                ('max_points', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('multi_select', 'Multi select'), ('true_false', 'True / false'), ('essay', 'Essay'), ('file_upload', 'File upload'), ('audio_recording', 'Recorded audio')], default='multiple_choice', max_length=20)),
                ('prompt', models.TextField()),
                ('audio', models.FileField(blank=True, help_text='Optional MP3 played with the question.', upload_to='questions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('explanation', models.TextField(blank=True, help_text='Shown after submission when answers are revealed.')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['assignment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('awarded_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['submission', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
