# Generated by Django 5.1.7 on 2026-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='kind',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes allowed once started. Leave empty for untimed work.', null=True),
        ),
    ]
