# Generated by Django 5.1.7 on 2026-09-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0001_initial'),
        ('study_materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Reference material students should read for this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='study_materials.studymaterial'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='Restrict to a single class. Leave empty to target the whole level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='students.studentclass'),
        ),
        migrations.AddField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.question'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_graded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student'),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.question'),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='assignments.questionchoice'),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='multi_answers', to='assignments.questionchoice'),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.submission'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Set when the upload answers one specific question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='assignments.question'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.submission'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'level', 'category'], name='assignment_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_at'], name='assignment_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__isnull', True), ('open_at__isnull', True), ('due_at__gt', models.F('open_at')), _connector='OR'), name='assignment_due_after_open'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_minutes__isnull', True), ('time_limit_minutes__gt', 0), _connector='OR'), name='assignment_time_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='assignment_max_attempts_min'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('assignment', 'order'), name='question_assignment_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='choice_question_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'status'], name='submission_asg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='submission_stu_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student', 'attempt_number'), name='submission_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='submission_attempt_min'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='answer_submission_question_uniq'),
        ),
        migrations.AddIndex(
            model_name='submissionfile',
            index=models.Index(fields=['submission'], name='submission_file_sub_idx'),
        ),
    ]
