# Generated by Django 5.1.7 on 2026-08-24 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, help_text='Optional MP3 played with the question.', upload_to='questions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('multi_select', 'Multi select'), ('true_false', 'True / false'), ('short_text', 'Short text'), ('essay', 'Essay'), ('file_upload', 'File upload'), ('audio_recording', 'Recorded audio')], default='multiple_choice', max_length=20),
        ),
    ]
