# Generated by Django 5.1.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_question_audio_alter_question_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple choice"),
                    ("multi_select", "Multi select"),
                    ("true_false", "True / false"),
                    ("essay", "Essay"),
                    ("file_upload", "File upload"),
                    ("audio_recording", "Recorded audio"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
    ]
