# Generated by Django 5.1.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_alter_question_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
