# Generated by Django 5.1.7 on 2026-09-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submission_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionUploadTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=100, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_upload_tickets', to='assignments.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tickets', to='assignments.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'created_at'], name='upload_ticket_sub_created_idx')],
            },
        ),
    ]
