# Generated by Django 5.1.7 on 2026-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='score_target',
            field=models.CharField(blank=True, choices=[('exercise_1', 'Exercise 1'), ('exercise_2', 'Exercise 2'), ('exercise_3', 'Exercise 3'), ('exercise_4', 'Exercise 4'), ('exercise_5', 'Exercise 5'), ('exercise_6', 'Exercise 6'), ('exercise_7', 'Exercise 7'), ('exercise_8', 'Exercise 8'), ('exercise_9', 'Exercise 9'), ('exercise_10', 'Exercise 10'), ('mid_term', 'Mid Term'), ('finals', 'Finals')], help_text='Score field updated when a submission is marked.', max_length=11, null=True),
        ),
    ]
