# Generated by Django 5.1.7 on 2026-09-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('superuser', 'Superuser'), ('student', 'Student')], default='teacher', help_text='Teacher (internal staff), Superuser (internal admin), or Student (public e-learning login only).', max_length=20)),
                ('email_verified', models.BooleanField(db_column='email_verified', default=False)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='AuthVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'auth verification',
                'db_table': 'auth_verification',
                'indexes': [models.Index(fields=['identifier'], name='auth_verification_ident_idx'), models.Index(fields=['expires_at'], name='auth_verification_expires_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(db_column='provider_id', max_length=100)),
                ('account_id', models.CharField(db_column='account_id', max_length=255)),
                ('issuer', models.CharField(help_text="better-auth account issuer, e.g. 'local:credential'.", max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True, db_column='access_token', null=True)),
                ('refresh_token', models.TextField(blank=True, db_column='refresh_token', null=True)),
                ('id_token', models.TextField(blank=True, db_column='id_token', null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, db_column='access_token_expires_at', null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, db_column='refresh_token_expires_at', null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auth account',
                'db_table': 'auth_account',
                'indexes': [models.Index(fields=['user'], name='auth_account_user_idx'), models.Index(fields=['provider_id'], name='auth_account_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('issuer', 'account_id'), name='auth_account_issuer_account_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('ip_address', models.CharField(blank=True, db_column='ip_address', max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='user_agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auth session',
                'db_table': 'auth_session',
                'indexes': [models.Index(fields=['user'], name='auth_session_user_idx'), models.Index(fields=['expires_at'], name='auth_session_expires_idx')],
            },
        ),
    ]
