# Generated by Django 5.1.7 on 2025-04-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('superuser', 'Superuser')], default='teacher', help_text='Select whether this user is a Teacher (staff) or a Superuser.', max_length=20),
        ),
    ]
